#!/usr/bin/env bash
echo 'BIENVENIDO AL PROGRAMA DE AUTOCREACION DE ARCHIVOS.SH'
echo '--------------------------------------'
echo "ingrese (1) para indicar directorio de autocreacion"
echo "ingrese (2) para que se cree automaticamente en su directorio actual"
read -p "ingrese su opcion: " cond
if [ $cond -eq 2 ];  then
	read -p "a continuacion ponga el nombre de su .sh: " archivo
	touch $archivo.sh && chmod +x $archivo.sh
	echo "#!/usr/bin/env bash" >> $archivo.sh
	nano $archivo.sh
	ls $(pwd)
elif [ $cond -eq 1 ]; then
	read -p "a continuacion ponga el nombre de su .sh: " archivo
	read -p "a continuacion ingrese la direccion donde desea crear la carpeta: " loc
	touch "$loc/$archivo.sh" && chmod +x "$loc/$archivo.sh"
	echo "#!/usr/bin/env bash" >> "$loc/$archivo.sh"
	ls $loc
	nano $loc/$archivo.sh
fi

