#!/usr/bin/env bash
echo 'BIENVENIDO AL PROGRAMA DE AUTOCREACION DE ARCHIVOS.SH'
while true; do
	echo '--------------------------------------'
	echo "ingrese (1) para indicar directorio de autocreacion"
	echo "ingrese (2) para que se cree automaticamente en su directorio actual"
	read -p "ingrese su opcion: " cond
	clear
	if [ $cond -eq 2 ];  then
		read -p "a continuacion ponga el nombre de su .sh: " archivo
		clear
		touch $archivo.sh && chmod +x $archivo.sh
		echo "#!/usr/bin/env bash" >> $archivo.sh
		echo "presione (1) para entrar en $archivo.sh"
		echo "presione 'ENTER' para terminar programa"
		read -p "ingrese su opcion: " cond
		if [ $cond -eq 1 ]; then
			nano $archivo.sh
		fi
		clear
		ls $(pwd)
		break
	elif [ $cond -eq 1 ]; then
		read -p "a continuacion ponga el nombre de su .sh: " archivo
		clear
		read -p "a continuacion ingrese la direccion donde desea crear la carpeta: " loc
		clear
		mkdir -p "$loc"
		touch "$loc/$archivo.sh" && chmod +x "$loc/$archivo.sh"
		echo "#!/usr/bin/env bash" >> "$loc/$archivo.sh"
		echo "presione (1) para entrar en $archivo.sh"
		echo "presione 'ENTER' para terminar programa"
		read -p "ingrese su opcion: " cond
		if [ $cond -eq 1 ]; then
			nano $loc/$archivo.sh
		fi
		clear
		ls $loc
		break
	fi
	echo 'ERROR: INGRESE UN VALOR CORRECTO'
done


